### ISSUE TITLE
Détection d'une plaque d'immatriculation depuis une image

### ISSUE THREAD

**Issue by JeromeVerkyndt** [He202120/Projet-Integration-Grp-2#14]

**Comment by Fscalais** [comment]
(BEGIN Sprint 1)

1. En tant qu'administrateur, je veux pouvoir détecter les plaques d'immatriculations des gens qui veulent rentrer dans les parkings et ainsi collecter des informations diverses. 
2. Description : 
    L'administrateur a la possibilité de voir qu'elle voiture est arrivé et a quelle heure et si elle est ou non toujours dans le parking et dans lequel.
3. Taches techniques : - Créer un route qui récupère les informations de la voiture présente dans le parking.
                                - Faire un script fonctionnel et précis qui détecte les plaques et sait les lires et les envoyer à la DB.
                                - Lier la partie électronique et la partie code.
